---
# Use Travis' Container Infrastructure
sudo: false

# Have Travis Setup Node, We Will Provide the Server Build Tools
language: node_js
node_js:
    - "node"

cache:
    directories:
        # Client Wrapper to Fix CPU Count
        - $TRAVIS_BUILD_DIR/sysconfcpus
        # Server Dependencies
        - $HOME/.stack

before_install:
    # Install sysconfcpus to Fix Client Build Times
    - if [ ! -d $TRAVIS_BUILD_DIR/sysconfcpus/bin ];
      then
        git clone https://github.com/obmarg/libsysconfcpus.git;
        cd libsysconfcpus;
        ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
        make && make install;
        cd ..;
      fi
    # Download Stack Binary from GitHub
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/.bin:$PATH
    - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 |
      tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
    # Install Client Dependencies
    - cd client
    - npm install
    - cd ..
    # Install Server Dependencies
    - cd server
    - stack --no-terminal --install-ghc install --only-dependencies
    - cd ..

script:
    # Build Client
    - cd client
    - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 npm run build
    - cd ..
    # Build Server
    - cd server
    - stack --no-terminal build
    - cd ..
