---

name:
    sese-website
version:
    1.4.8.0
synopsis:
    The API Server for Southern Exposure's Retail Website
category:
    Application
github:
    Southern-Exposure-Seed-Exchange/southernexposure.com
license:
    GPL-3.0
author:
    "Pavan Rikhi"
maintainer:
    "pavan.rikhi@gmail.com"
copyright:
    2017-2020 Pavan Rikhi
bug-reports:
    http://bugs.sleepanarchy.com/projects/sese-website/issues/new

description: >
    This is JSON API server for Southern Exposure Seed Exchange's Retail
    E-Commerce Website. It uses Persistent for DB management & Servant for
    routing. It is paired with an Elm frontend available in the same
    repository.


ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -O2

# TODO: Split up between lib/exe sections unless used throughout
dependencies:
    - base >= 4.7 && < 5
    - aeson
    - async
    - base64-bytestring
    - bcrypt
    - blaze-html
    - blaze-markup
    - bytestring
    - ca-province-codes
    - cereal
    - cereal-text
    - containers
    - cryptonite
    - data-default
    - directory
    - esqueleto
    - fast-logger
    - filepath
    - hostname
    - http-api-data
    - http-client
    - http-media
    - http-types
    - immortal-queue
    - iso3166-country-codes
    - markdown
    - mime-mail
    - monad-control
    - mtl
    - pandoc
    - persistent
    - persistent-template
    - pureMD5
    - resource-pool
    - req
    - safe-exceptions
    - scientific
    - servant-auth-cookie
    - servant-server
    - sitemap-gen
    - smtp-mail
    - state-codes
    - stm
    - stripe-core
    - stripe-haskell
    - tagsoup
    - text
    - time
    - typed-process
    - unordered-containers
    - uuid
    - wai
    - xmlgen
    - xss-sanitize


library:
    source-dirs: src
    exposed-modules:
        - Api
        - Auth
        - Avalara
        - Cache
        - Config
        - Images
        - Models
        - Models.Fields
        - Models.PersistJSON
        - Routes.Admin.ShippingMethods
        - Routes.CommonData
        - Routes.StoneEdge
        - StoneEdge
        - Workers

tests:
    sese-website-test:
        main:
            Spec.hs
        source-dirs:
            test
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - sese-website
            - tasty
            - tasty-hedgehog
            - tasty-hunit
            - hedgehog
            - HUnit
            - raw-strings-qq

_script-def: &script-defaults
    source-dirs: scripts
    other-modules:
        - Utils
    ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N

executables:
    sese-website-exe:
        main:
            Main.hs
        source-dirs:
            app
        ghc-options:
            - -threaded
            - -rtsopts
            - '"-with-rtsopts=-T -N"'
        dependencies:
            - sese-website
            - fast-logger
            - monad-control
            - monad-logger
            - persistent-postgresql
            - stripe-core
            - unix
            - wai-extra
            - warp

    clean-carts:
        main: CleanCarts.hs
        <<: *script-defaults
        other-modules: []
        dependencies:
            - sese-website
            - esqueleto
            - monad-logger
            - persistent-postgresql
            - text

    export-odd-weights:
        main: ExportOddWeights.hs
        <<: *script-defaults
        other-modules: []
        dependencies:
            - sese-website
            - monad-logger
            - persistent-postgresql
            - text

    export-products:
        main: ExportProducts.hs
        <<: *script-defaults
        other-modules: []
        dependencies:
            - sese-website
            - bytestring
            - cassava
            - esqueleto
            - monad-logger
            - persistent-postgresql
            - text

    update-product-descriptions:
        main: UpdateProductDescriptions.hs
        <<: *script-defaults
        other-modules: []
        dependencies:
            - sese-website
            - bytestring
            - cassava
            - monad-logger
            - persistent-postgresql
            - text
            - vector

    update-product-prices:
        main: UpdateProductPrices.hs
        <<: *script-defaults
        other-modules: []
        dependencies:
            - sese-website
            - bytestring
            - cassava
            - monad-logger
            - persistent-postgresql
            - text
            - vector

    import-category-keywords:
        main: ImportCategoryKeywords.hs
        <<: *script-defaults
        other-modules: []
        dependencies:
            - sese-website
            - bytestring
            - cassava
            - esqueleto
            - monad-logger
            - persistent-postgresql
            - text
            - vector

    import-product-keywords:
        main: ImportProductKeywords.hs
        <<: *script-defaults
        other-modules: []
        dependencies:
            - sese-website
            - bytestring
            - cassava
            - monad-logger
            - persistent-postgresql
            - text
            - vector

    import-product-suggestions:
        main: ImportProductSuggestions.hs
        <<: *script-defaults
        other-modules: []
        dependencies:
            - sese-website
            - bytestring
            - cassava
            - monad-logger
            - persistent-postgresql
            - text
            - vector

    export-products-racks:
        main: ExportProductsRacks.hs
        <<: *script-defaults
        other-modules: []
        dependencies:
            - sese-website
            - bytestring
            - cassava
            - esqueleto
            - monad-logger
            - persistent-postgresql
            - text
            - time
