---

name:
    sese-website
version:
    0.9.0.0
synopsis:
    The API Server for Southern Exposure's Retail Website
category:
    Application
github:
    Southern-Exposure-Seed-Exchange/southernexposure.com
license:
    GPL-3.0
license-file:
    ../LICENSE
author:
    "Pavan Rikhi"
maintainer:
    "pavan.rikhi@gmail.com"
copyright:
    2017-2019 Pavan Rikhi
bug-reports:
    http://bugs.sleepanarchy.com/projects/sese-website/issues/new

description: >
    This is JSON API server for Southern Exposure Seed Exchange's Retail
    E-Commerce Website. It uses Persistent for DB management & Servant for
    routing. It is paired with an Elm frontend available in the same
    repository.

extra-source-files:
    - ../README.rst
    - ../LICENSE


ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

# TODO: Split up between lib/exe sections unless used throughout
dependencies:
    - base >= 4.7 && < 5
    - aeson
    - async
    - base64-bytestring
    - bcrypt
    - blaze-html
    - blaze-markup
    - bytestring
    - ca-province-codes
    - cereal
    - cereal-text
    - containers
    - cryptonite
    - data-default
    - directory
    - esqueleto
    - filepath
    - HaskellNet
    - HaskellNet-SSL
    - http-api-data
    - iso3166-country-codes
    - markdown
    - mtl
    - pandoc
    - persistent
    - persistent-template
    - pureMD5
    - resource-pool
    - safe-exceptions
    - scientific
    - servant-auth-cookie
    - servant-server
    - state-codes
    - stm
    - stripe-core
    - stripe-haskell
    - tagsoup
    - text
    - time
    - typed-process
    - unordered-containers
    - uuid
    - wai
    - xmlgen
    - xss-sanitize


library:
    source-dirs: src
    exposed-modules:
        - Api
        - Auth
        - Cache
        - Config
        - Images
        - Models
        - Models.Fields
        - Routes.CommonData
        - Routes.StoneEdge
        - StoneEdge

tests:
    sese-website-test:
        main:
            Spec.hs
        source-dirs:
            test
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - sese-website
            - tasty
            - tasty-hedgehog
            - tasty-hunit
            - hedgehog
            - HUnit
            - raw-strings-qq

_script-def: &script-defaults
    source-dirs: scripts
    other-modules:
        - Utils
    ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N

executables:
    sese-website-exe:
        main:
            Main.hs
        source-dirs:
            app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - sese-website
            - monad-logger
            - persistent-postgresql
            - stripe-core
            - wai-extra
            - warp

    data-migration:
        main: DataMigration.hs
        <<: *script-defaults
        dependencies:
            - sese-website
            - bytestring
            - containers
            - filepath
            - io-streams
            - iso3166-country-codes
            - monad-logger
            - mysql-haskell
            - persistent
            - persistent-postgresql
            - resource-pool
            - state-codes
            - text
            - transformers
            - uuid

    export-odd-weights:
        main: ExportOddWeights.hs
        <<: *script-defaults
        other-modules: []
        dependencies:
            - sese-website
            - monad-logger
            - persistent-postgresql
            - text

    image-migration:
        main: ImageMigration.hs
        <<: *script-defaults
        other-modules: []
        dependencies:
            - sese-website
            - bytestring
            - directory
            - filepath
            - monad-logger
            - persistent-postgresql
            - text

    clean-database:
        main: CleanDatabase.hs
        <<: *script-defaults
        other-modules: []
        dependencies:
            - sese-website
            - bytestring
            - monad-logger
            - persistent
            - persistent-postgresql
            - time
            - transformers
