---
# yamllint disable rule:line-length

name: CI Build

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Needed to build the frontend
      - run:
          echo "CXXFLAGS=-std=c++17" >> $GITHUB_ENV
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: client/package-lock.json
      - name: Cache Client Dependencies
        uses: actions/cache@v4
        with:
          path: client/node_modules
          key: client-${{ github.ref }}-${{ github.sha }}

      - name: Install Client Dependencies
        working-directory: client
        run: npm ci
      - name: Build Client Project
        working-directory: client
        run: npm run build

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '8.10.7'
          enable-stack: true
          stack-version: 'latest'
      # Avoid installing GHC via stack
      - run: |
          stack config set system-ghc true --global
          stack config set install-ghc false --global
      - uses: actions/cache@v4
        with:
          path: |
            ~/.stack
            server/.stack-work
          key: server-${{ hashFiles('server/package.yaml', 'server/stack.yaml', 'server/stack.yaml.lock') }}
      - name: Install Server Dependencies
        working-directory: server
        run: stack build --ghc-options="-Werror -O1" --only-dependencies
      - name: Build Server Project
        working-directory: server
        run: stack build --ghc-options="-Werror -O1"
